name: test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1

      - name: docker build
        run: docker build -t ros-go .

      - name: go test
        run: docker run -it --rm ros-go go test -v
