name: test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - name: go install
        uses: actions/setup-go@v1
        with:
          go-version: 1.13

      - name: checkout
        uses: actions/checkout@v1

      - name: ros install
        uses: ros-tooling/setup-ros@v0.1
        with:
          required-ros-distributions: melodic

      - name: test
        run: |
          go test -v
